together_today/views/auth.py
import uuid
import os
from flask import current_app as app
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user, logout_user

from together_today.forms.auth import RegisterForm, LoginForm
from together_today.models import User, Profile, Register_Code ,db
from together_today.utils.crypto import hash_password, verify_password

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()

    if request.method == "POST":
        if login_form.validate_on_submit():
            username = login_form.data["username"]
            password = login_form.data["password"]

            user = User.query.filter_by(username=username).first()

            if not user:
                flash("Invalid username and/or password", category="form_error")
                return render_template("auth/login.html", form=login_form)

            if verify_password(password, user.password):
                flash("Successfully logged-in!", category="success")
                login_user(user)

                nxt = login_form.data.get("next", None)
                if nxt and nxt.startswith("/"):
                    return redirect(nxt)


                return redirect(
                    url_for(
                        "profile.single_profile",
                        username=username
                    )
                )

            flash("Invalid username and/or password", category="form_error")
            return render_template("auth/login.html", form=login_form)

    nxt = request.args.get("next", None)
    if nxt and nxt.startswith("/"):
        login_form.next.data = nxt

    return render_template("auth/login.html", form=login_form)


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    register_form = RegisterForm()

    if request.method == "POST":
        if register_form.validate_on_submit():
            username = register_form.data["username"]
            first_name = register_form.data["first_name"]
            last_name = register_form.data["last_name"]
            picture = register_form.data["picture"]
            register_code = register_form.data["register_code"]
            password = hash_password(register_form.data["password"])

            username_taken = User.query.filter_by(username=username).first()

            is_valid_code = False

            if username_taken:
                flash("User with this username already exists!", category="form_error")
                return render_template("auth/register.html", form=register_form)

            register_codes = Register_Code.query.all()

            for valid_register_code in register_codes:
                if register_code == valid_register_code.code:
                    is_valid_code = True
                    db.session.delete(valid_register_code)
                    db.session.commit()
                    break

            if not is_valid_code:
                flash("Wrong registration code!", category="form_error")
                return render_template("auth/register.html", form=register_form)


            if picture:
                extension = os.path.splitext(picture.filename)[1]
                picture_name = f"{uuid.uuid4()}{extension}"
                picture.save(os.path.join(app.config["UPLOADS_FOLDER"], picture_name))
            else:
                picture_name = "default.png"

            user = User(
                username=username,
                password=password,
            )

            profile = Profile(
                first_name=first_name,
                last_name=last_name,
                user=user,
                picture=picture_name,
            )

            db.session.add_all([user, profile])
            db.session.commit()

            flash("Successfully registered, you can now log in!", category="success")
            return redirect(url_for("auth.login"))

    # GET request or invalid POST request
    return render_template("auth/register.html", form=register_form)


@auth_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash("Successfully logged out!", category="success")
    return redirect(url_for("general.index"))

together_today/views/general.py
from datetime import datetime, date
from flask import Blueprint, render_template, Response, jsonify, send_from_directory
from flask import current_app as app
from flask_login import login_required
from together_today.models import Photo_and_Message, Current_Photo, db
general_blueprint = Blueprint("general", __name__)


@general_blueprint.route("/", methods=["GET"])
def index():
        current_photo = Current_Photo.query.filter_by(id=1).first()
        if current_photo:
                photo_and_message = Photo_and_Message.query.filter_by(id=current_photo.counter).first()
        if not current_photo or current_photo.counter == 0:
                return render_template("general/index.html")
        else:
                return render_template("general/index.html", photo_and_message=photo_and_message)
                


@general_blueprint.route('/time_feed') 
@login_required
def time_feed():
        def generate():
                yield datetime.now().strftime("%H:%M:%S")
        return Response(generate(), mimetype='text') 


@general_blueprint.route('/check_for_photo') 
@login_required
def check_for_photo():
        current_date = date.today()
        photo_date_db = Current_Photo.query.filter_by(id=1).first_or_404()


        data_splitted = photo_date_db.current_date.split("-")
        days_difference = current_date - date(int(data_splitted[0]), int(data_splitted[1]), int(data_splitted[2]))
        
        new_photo = False

        if days_difference.days != 0:
                photo_and_message = Photo_and_Message.query.filter_by(id=photo_date_db.counter+days_difference.days).first()
                if photo_and_message != None:
                        photo_date_db.current_photo = photo_and_message.photo_name
                        photo_date_db.message = photo_and_message.message
                        photo_date_db.counter += days_difference.days
                        photo_date_db.current_date = str(current_date)
                        db.session.commit()
                        new_photo = True

        if new_photo:
                return jsonify({"status": "Accepted"}), 202

        return jsonify({"status": "OK"}), 200


@general_blueprint.route("/index/uploads/<path:filename>")
@login_required
def index_photo(filename):
    return send_from_directory(app.config["PHOTOS_FOLDER"], filename)

together_today/templates/general/index.html
{% extends 'base.html' %}

{% block title %}
  Welcome
{% endblock %}


{% block content %}
  <div class="container mx-auto my-5 flex justify-center flex-col items-center"> 
    
    {% if not current_user.is_authenticated %}
    <h1 class="text-4xl text-center font-bold mt-24 dark:text-slate-200">Welcome to Together Today!</h1>

        <div class="bg-white w-2/5 h-4/5 mt-4 rounded-3xl mt-24 mb-10 border-8 border-solid border-purple-400 dark:border-slate-600 shadow-2xl dark:bg-slate-400">
          
          <div class="mt-3 flex justify-center">
              <img src="{{ url_for('static', filename='img/raccoon_index.jpg') }}" class="rounded-full w-72 mb-10 border-4 border-white dark:border-slate-100" alt="Raccoon Love <33" />
          </div>
          
          <div class="place-self-end mb-10 flex justify-center">
            <a href="{{ url_for('auth.login') }}"
              class="px-6 py-3 border-4  text-white  bg-pink-300 rounded-full hover:bg-pink-400 hover:text-white-200 w-28 flex justify-center dark:bg-slate-600 dark:hover:bg-slate-700">Log In</a>
          
            <a href="{{ url_for('auth.register') }}"
              class="ml-6 px-6 py-3 border-4 text-white  bg-pink-300 rounded-full hover:bg-pink-400 hover:text-white-200 w-28 flex justify-center dark:bg-slate-600 dark:hover:bg-slate-700">Register</a>
           
          </div>
        </div>
        {% else %}
          <p class="text-3xl flex justify-center font-semibold 
            bg-gradient-to-r bg-clip-text  text-transparent 
            from-rose-600 via-cyan-400 to-fuchsia-600
            animate-text pb-1">Your special photo at 00:00 everyday!</p>

          <p id="clock" class="text-5xl flex justify-center mt-2 dark:text-slate-200">00:00:00</p>

          {% if photo_and_message %}
            <img src="{{ url_for('general.index_photo', filename=photo_and_message.photo_name ) }}" class="mt-4 w-2/6 h-2/6 border-8 border-solid border-purple-400 shadow-2xl flex justify-center rounded-md dark:border-slate-600"
              alt="Love photo <33" />

            <div class="bg-white rounded-full mt-8 w-2/5 h-36 flex justify-center text-center items-center 
            border-8 border-solid border-purple-400 shadow-2xl break-words dark:border-slate-600">
               <p class="text-lg italic font-serif p-4">{{ photo_and_message.message }}</p>
            </div>
            {% else %}
              <img src="{{ url_for('static', filename='img/raccoon_index.jpg') }}"
                class="mt-4 w-2/6 h-2/6 border-8 border-solid border-purple-400 shadow-2xl flex justify-center rounded-md dark:border-slate-600"
                alt="Raccoon Love <33" />
              
              <div class="bg-white rounded-full mt-8 w-2/5 h-36 flex justify-center text-center items-center 
                          border-8 border-solid border-purple-400 shadow-md break-words dark:bg-slate-50 dark:border-slate-600">
                <p class="text-lg italic font-serif p-4 bg-transparent">Już niedługo!</p>
              </div>
            {% endif %}
      {% endif %}
     
      
  </div>

  {% if current_user.is_authenticated %}
  <script>
    var clock = document.getElementById("clock");

    setInterval(() => {
      fetch("{{ url_for('general.time_feed') }}")
        .then(response => {
          response.text().then(t => { clock.innerHTML = t })
        });
    }, 1000);  
    

    setInterval(() => {
        fetch("{{ url_for('general.check_for_photo') }}")
          .then(response => {
            if (response.status == 200 || response.status == 404) {
              return 0;
            } else {
              window.location.reload();
            }
          });
      }, 1000); 

  </script>
  {% endif %}

{% endblock %}