together_today/forms/profile.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, EmailField, SubmitField, FileField
from wtforms.validators import Email, Length, EqualTo, Optional


class EditForm(FlaskForm):
    first_name = StringField("First Name", validators=[Optional()], render_kw={"placeholder": "John"})
    last_name = StringField("Last Name", validators=[Optional()], render_kw={"placeholder": "Doe"})
    username = StringField("Username", validators=[Optional()], render_kw={"placeholder": "PussyDestroyer69"})
    picture = FileField("Picture", validators=[Optional()])

    new_password = PasswordField(
        "New Password", validators=[Optional(), Length(min=8, max=64)]
    )
    confirm_password = PasswordField(
        "Confirm New Password",
        validators=[Optional(), Length(min=8, max=64), EqualTo("new_password")],
    )

    submit = SubmitField("Save")

together_today/views/profile.py
import uuid
import os
from flask import (
    Blueprint,
    jsonify,
    render_template,
    request,
    flash,
    url_for,
    redirect,
    send_from_directory,
    abort,
)
from flask import current_app as app
from flask_login import login_required, current_user

from together_today.forms.profile import EditForm
from together_today.utils.crypto import hash_password, verify_password
from together_today.utils.decorators.admin import admin_required

from together_today.models import db, Profile, User

profile_blueprint = Blueprint("profile", __name__)



@profile_blueprint.route("/profile/<username>", methods=["GET"])
@login_required
def single_profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template(
        "profile/profile.html",
        user=user,
    )




@profile_blueprint.route("/profile/uploads/<path:filename>")
@login_required
def profile_picture(filename):
    return send_from_directory(app.config["UPLOADS_FOLDER"], filename)


@profile_blueprint.route("/profile/<profile_id>/edit", methods=["GET", "POST"])
@login_required
def edit(profile_id):
    profile = Profile.query.filter_by(id=profile_id).first_or_404()

    if current_user == profile.user or current_user.is_admin:
        edit_form = EditForm(
            first_name=profile.first_name,
            last_name=profile.last_name,
            username=profile.user.username,
        )

        if request.method == "POST":
            if edit_form.validate_on_submit():
                username = edit_form.data["username"]
                first_name = edit_form.data["first_name"]
                last_name = edit_form.data["last_name"]
                picture = edit_form.data["picture"]
                new_password = edit_form.data["new_password"]

                if username:
                    username_taken = User.query.filter_by(username=username).first()
                    if username_taken:
                        if username_taken.username != profile.user.username:
                            flash(
                                "User with this username already exists",
                                category="form_error",
                            )
                            return render_template(
                                "profile/edit.html", form=edit_form, profile=profile
                            )
                    else:
                        profile.user.username = username

                if last_name:
                    profile.last_name = last_name

                if first_name:
                    profile.first_name = first_name

                if new_password:
                    if verify_password(new_password, profile.user.password):
                        flash(
                            "New password can not be the same as current password",
                            category="form_error",
                        )
                        return render_template(
                            "profile/edit.html", form=edit_form, profile=profile
                        )

                    profile.user.password = hash_password(new_password)

                if picture:
                    photo_name = profile.picture
                    if photo_name != "default.png":
                        os.remove(os.path.join(app.config["UPLOADS_FOLDER"], photo_name))
                    extension = os.path.splitext(picture.filename)[1]
                    picture_name = f"{uuid.uuid4()}{extension}"
                    picture.save(
                        os.path.join(app.config["UPLOADS_FOLDER"], picture_name)
                    )
                    profile.picture = picture_name

                db.session.commit()

                return redirect(
                    url_for("profile.single_profile", username=profile.user.username)
                )

        # GET request or invalid POST request
        return render_template("profile/edit.html", form=edit_form, profile=profile)

    return abort(403)


@profile_blueprint.route("/profile/<profile_id>/delete", methods=["DELETE"])
@login_required
@admin_required
def delete_profile(profile_id):
    # delete_profile in reality deletes profile with the user and all the data
    profile = Profile.query.filter_by(id=profile_id).first_or_404()
    db.session.delete(profile.user)
    db.session.commit()

    return jsonify({"status": "OK"}), 200


@profile_blueprint.route("/picture/<profile_id>/delete", methods=["DELETE"])
@login_required
def delete_profile_picture(profile_id):
    profile = Profile.query.filter_by(id=profile_id).first_or_404()

    if current_user == profile.user:
        photo_name = profile.picture
        os.remove(os.path.join(app.config["UPLOADS_FOLDER"], photo_name))
        profile.picture = "default.png"
        db.session.commit()
        return jsonify({"status": "OK"}), 200

    return jsonify({"status": "OK"}), 200

together_today/templates/profile/edit.html
{% extends 'base.html' %}

{% block title %}
  Edit {{ profile.user.username }}
{% endblock %}

{% block content %}
  <div class="container mx-auto">

    <div class="max-w-md mx-auto">
      {% include '_partials/form_errors.html' %}

      <form action="{{ url_for('profile.edit', profile_id=profile.id) }}" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mt-4">
          {{ form.first_name.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.first_name(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
                focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white" ) }}


          {% for error in form.first_name.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="mt-4">
          {{ form.last_name.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.last_name(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
                focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white") }}

          {% for error in form.last_name.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="mt-4">
          {{ form.username.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.username(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
                focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white") }}

          {% for error in form.username.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="mt-4">
          {{ form.picture.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.picture(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
          focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white") }}
        
          {% for error in form.picture.errors %}
          <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>


        <div class="mt-4">
          {{ form.new_password.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.new_password(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
                focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white") }}

          {% for error in form.new_password.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="mt-4">
          {{ form.confirm_password.label(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
          {{ form.confirm_password(class="bg-gray-50 border-4 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500
                focus:border-red-500 block w-full p-2.5 dark:bg-slate-400 dark:border-slate-500 dark:text-white") }}

          {% for error in form.confirm_password.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="mt-4">
          {{ form.submit (class="w-full text-white bg-violet-400 hover:bg-violet-500 focus:ring-4
          focus:outline-none focus:ring-violet-300 dark:focus:ring-slate-400 font-medium rounded-lg text-sm w-full px-5 py-2.5
          text-center
          cursor-pointer dark:bg-slate-800 dark:hover:bg-slate-900") }}
        </div>
      </form>

    </div>
  </div>


{% endblock %}

together_today/templates/profile/profile.html
{% extends 'base.html' %}

{% block title %}
  {{ user.username }} profile
{% endblock %}

{% block content %}
  <div class="container mx-auto mt-5">
    {% include "_partials/flashes.html" %}

      <div class="w-full max-w-md mx-auto px-3">
        <div class="max-w-sm bg-white rounded-lg border-2 border-gray-200 dark:bg-slate-400 dark:border-slate-500 shadow-md">
          <div class="flex flex-col items-center pb-10 pt-4">
            {% if user.profile.picture != "default.png" %}
              <img class="mb-3 w-24 h-24 rounded-full shadow-lg border-2" src="{{ url_for('profile.profile_picture', filename=user.profile.picture ) }}"
                 alt="{{ user.username }} profile picture" />
            {% else %}
              <img class="mb-3 w-24 h-24 rounded-full shadow-lg border-2" src="{{ url_for('static', filename='img/default.png') }}"
                alt="{{ user.username }} profile picture">
            {% endif %}
            <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-slate-100">
              {{ user.profile.first_name }} {{ user.profile.last_name }}
            </h5>
            <span class="text-sm text-gray-500 dark:text-slate-50">@{{ user.username }}</span>

              <div class="flex mt-4 space-x-3 md:mt-6">
                <a href="{{ url_for('profile.edit', profile_id=user.profile.id) }}"
                   class="inline-flex w-full items-center py-2 px-4 text-sm font-medium text-center text-white bg-violet-400 hover:bg-violet-500 
                   focus:ring-4 focus:outline-none focus:ring-violet-300 font-medium rounded-lg text-sm w-full px-5 py-2.5 text-center cursor-pointer
                   dark:bg-slate-500 dark:hover:bg-slate-600 dark:focus:ring-slate-200">
                  Edit <i class="fa-solid fa-pen ml-1.5"></i>
                </a>

              </div>
            

            {% if current_user.profile.picture != 'default.png' %}
            <div class="inline-flex ml-3 mt-3 font-semibold">
              <button data-picture-url="{{ url_for('profile.delete_profile_picture', profile_id=user.profile.id ) }}"
                class="inline-flex w-full items-center py-2 px-4 text-sm font-medium text-center text-white bg-violet-400 hover:bg-violet-500 
                focus:ring-4 focus:outline-none focus:ring-violet-300 font-medium rounded-lg text-sm w-full px-5 py-2.5 text-center cursor-pointer 
                dark:bg-slate-500 dark:hover:bg-slate-600 dark:focus:ring-slate-200">
                Delete Picture
                <i class="fa-solid fa-xmark ml-3"></i>
              </button>
            </div>
            {% endif %}
          </div>

        </div>
    </div>

{% endblock %}

{% block scripts %}
  <script>
    
    const pictureBtns = Array.from(document.querySelectorAll("[data-picture-url]"));
      pictureBtns.forEach(btn => {
        btn.addEventListener("click", () => {
          if (confirm("Do you really want to delete your profile picture?")) {
          const url = btn.getAttribute("data-picture-url");
          if (url !== "") {
            fetch(url, {
              method: "DELETE"
            }).then(res => {
              window.location.reload();
            });
          }
        }
        });
      });

  </script>
{% endblock %}