together_today/views/auth.py
import uuid
import os
from flask import current_app as app
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user, logout_user

from together_today.forms.auth import RegisterForm, LoginForm
from together_today.models import User, Profile, Register_Code ,db
from together_today.utils.crypto import hash_password, verify_password

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()

    if request.method == "POST":
        if login_form.validate_on_submit():
            username = login_form.data["username"]
            password = login_form.data["password"]

            user = User.query.filter_by(username=username).first()

            if not user:
                flash("Invalid username and/or password", category="form_error")
                return render_template("auth/login.html", form=login_form)

            if verify_password(password, user.password):
                flash("Successfully logged-in!", category="success")
                login_user(user)

                nxt = login_form.data.get("next", None)
                if nxt and nxt.startswith("/"):
                    return redirect(nxt)


                return redirect(
                    url_for(
                        "profile.single_profile",
                        username=username
                    )
                )

            flash("Invalid username and/or password", category="form_error")
            return render_template("auth/login.html", form=login_form)

    nxt = request.args.get("next", None)
    if nxt and nxt.startswith("/"):
        login_form.next.data = nxt

    return render_template("auth/login.html", form=login_form)


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    register_form = RegisterForm()

    if request.method == "POST":
        if register_form.validate_on_submit():
            username = register_form.data["username"]
            first_name = register_form.data["first_name"]
            last_name = register_form.data["last_name"]
            picture = register_form.data["picture"]
            register_code = register_form.data["register_code"]
            password = hash_password(register_form.data["password"])

            username_taken = User.query.filter_by(username=username).first()

            is_valid_code = False

            if username_taken:
                flash("User with this username already exists!", category="form_error")
                return render_template("auth/register.html", form=register_form)

            register_codes = Register_Code.query.all()

            for valid_register_code in register_codes:
                if register_code == valid_register_code.code:
                    is_valid_code = True
                    db.session.delete(valid_register_code)
                    db.session.commit()
                    break

            if not is_valid_code:
                flash("Wrong registration code!", category="form_error")
                return render_template("auth/register.html", form=register_form)


            if picture:
                extension = os.path.splitext(picture.filename)[1]
                picture_name = f"{uuid.uuid4()}{extension}"
                picture.save(os.path.join(app.config["UPLOADS_FOLDER"], picture_name))
            else:
                picture_name = "default.png"

            user = User(
                username=username,
                password=password,
            )

            profile = Profile(
                first_name=first_name,
                last_name=last_name,
                user=user,
                picture=picture_name,
            )

            db.session.add_all([user, profile])
            db.session.commit()

            flash("Successfully registered, you can now log in!", category="success")
            return redirect(url_for("auth.login"))

    # GET request or invalid POST request
    return render_template("auth/register.html", form=register_form)


@auth_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash("Successfully logged out!", category="success")
    return redirect(url_for("general.index"))

together_today/views/profile.py
import uuid
import os
from flask import (
    Blueprint,
    jsonify,
    render_template,
    request,
    flash,
    url_for,
    redirect,
    send_from_directory,
    abort,
)
from flask import current_app as app
from flask_login import login_required, current_user

from together_today.forms.profile import EditForm
from together_today.utils.crypto import hash_password, verify_password
from together_today.utils.decorators.admin import admin_required

from together_today.models import db, Profile, User

profile_blueprint = Blueprint("profile", __name__)



@profile_blueprint.route("/profile/<username>", methods=["GET"])
@login_required
def single_profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template(
        "profile/profile.html",
        user=user,
    )




@profile_blueprint.route("/profile/uploads/<path:filename>")
@login_required
def profile_picture(filename):
    return send_from_directory(app.config["UPLOADS_FOLDER"], filename)


@profile_blueprint.route("/profile/<profile_id>/edit", methods=["GET", "POST"])
@login_required
def edit(profile_id):
    profile = Profile.query.filter_by(id=profile_id).first_or_404()

    if current_user == profile.user or current_user.is_admin:
        edit_form = EditForm(
            first_name=profile.first_name,
            last_name=profile.last_name,
            username=profile.user.username,
        )

        if request.method == "POST":
            if edit_form.validate_on_submit():
                username = edit_form.data["username"]
                first_name = edit_form.data["first_name"]
                last_name = edit_form.data["last_name"]
                picture = edit_form.data["picture"]
                new_password = edit_form.data["new_password"]

                if username:
                    username_taken = User.query.filter_by(username=username).first()
                    if username_taken:
                        if username_taken.username != profile.user.username:
                            flash(
                                "User with this username already exists",
                                category="form_error",
                            )
                            return render_template(
                                "profile/edit.html", form=edit_form, profile=profile
                            )
                    else:
                        profile.user.username = username

                if last_name:
                    profile.last_name = last_name

                if first_name:
                    profile.first_name = first_name

                if new_password:
                    if verify_password(new_password, profile.user.password):
                        flash(
                            "New password can not be the same as current password",
                            category="form_error",
                        )
                        return render_template(
                            "profile/edit.html", form=edit_form, profile=profile
                        )

                    profile.user.password = hash_password(new_password)

                if picture:
                    photo_name = profile.picture
                    if photo_name != "default.png":
                        os.remove(os.path.join(app.config["UPLOADS_FOLDER"], photo_name))
                    extension = os.path.splitext(picture.filename)[1]
                    picture_name = f"{uuid.uuid4()}{extension}"
                    picture.save(
                        os.path.join(app.config["UPLOADS_FOLDER"], picture_name)
                    )
                    profile.picture = picture_name

                db.session.commit()

                return redirect(
                    url_for("profile.single_profile", username=profile.user.username)
                )

        # GET request or invalid POST request
        return render_template("profile/edit.html", form=edit_form, profile=profile)

    return abort(403)


@profile_blueprint.route("/profile/<profile_id>/delete", methods=["DELETE"])
@login_required
@admin_required
def delete_profile(profile_id):
    # delete_profile in reality deletes profile with the user and all the data
    profile = Profile.query.filter_by(id=profile_id).first_or_404()
    db.session.delete(profile.user)
    db.session.commit()

    return jsonify({"status": "OK"}), 200


@profile_blueprint.route("/picture/<profile_id>/delete", methods=["DELETE"])
@login_required
def delete_profile_picture(profile_id):
    profile = Profile.query.filter_by(id=profile_id).first_or_404()

    if current_user == profile.user:
        photo_name = profile.picture
        os.remove(os.path.join(app.config["UPLOADS_FOLDER"], photo_name))
        profile.picture = "default.png"
        db.session.commit()
        return jsonify({"status": "OK"}), 200

    return jsonify({"status": "OK"}), 200

together_today/templates/_partials/flashes.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% for category, message in messages %}

    {% if category == "error" %}
      {% set div_classes = "bg-red-100 border-red-400 text-red-700" %}
      {% set icon_classes = "text-red-500" %}
      {% set text = "Error!" %}
    {% endif %}

    {% if category == "success" %}
      {% set div_classes = "bg-green-100 border-green-400 text-green-700" %}
      {% set icon_classes = "text-green-500" %}
      {% set text = "Success!" %}
    {% endif %}

    {% if category == "warning" %}
      {% set div_classes = "bg-yellow-100 border-yellow-400 text-yellow-700" %}
      {% set icon_classes = "text-yellow-500" %}
      {% set text = "Warning" %}
    {% endif %}

    {% if category == "info" %}
      {% set div_classes = "bg-blue-100 border-blue-400 text-blue-700" %}
      {% set icon_classes = "text-blue-500" %}
      {% set text = "Info" %}
    {% endif %}

    <div class="border px-4 py-3 rounded relative {{ div_classes }}" id="alert-{{ loop.counter }}">
      <strong class="font-bold">{{ text }}</strong>
      <span class="block sm:inline">{{ message }}</span>
      <button class="absolute top-0 bottom-0 right-0 px-4 py-3" data-dismiss-target="#alert-{{ loop.counter }}">
        <i class="h-6 w-6 fa-solid fa-circle-xmark {{ icon_classes }}"></i>
      </button>
    </div>
  {% endfor %}
{% endwith %}

together_today/templates/_partials/form_errors.html
{% for msg in get_flashed_messages(category_filter='form_error') %}
  <div class="flex p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg mt-4">
    <i class="fa-solid fa-exclamation flex-shrink-0 text-center inline w-5 h-5 mr-3 mt-0.5"></i>
    <div>{{ msg }}</div>
  </div>
{% endfor %}

together_today/templates/_partials/nav.html
<nav class="bg-purple-300 dark:bg-slate-800 px-2 sm:px-4 py-3 rounded-md shadow-md">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

  
      <a href="{{ url_for('general.index') }}" class="flex items-center">
        <img src="{{ url_for('static', filename='img/hearts_logo.png') }}" class="mr-3 h-12" alt="Together Today Logo" />
        <span class="self-center font-semibold text-3xl dark:text-slate-200">T<img src="{{ url_for('static', filename='img/heart_icon.png') }}" alt="heart_icon.png" class="w-6 h-6 inline mx-0.5">gether 
          T<img src="{{ url_for('static', filename='img/heart_icon.png') }}" alt="heart_icon.png" class="w-6 h-6 inline mx-0.5">day</span>
      </a>
  
      {% if current_user.is_authenticated %}
          <a href="{{ url_for('profile.single_profile', username=current_user.username) }}" class="flex items-center">
            {% if current_user.profile.picture != "default.png" %}
            <img class="mb-3 w-20 h-20 rounded-full shadow-lg inline border-2"
              src="{{ url_for('profile.profile_picture', filename= current_user.profile.picture ) }}"
              alt="{{  current_user.username }} profile picture" />
            {% else %}
            <img class="mb-3 w-14 h-14 rounded-full shadow-lg inline border-2" src="{{ url_for('static', filename='img/default.png') }}"
              alt="{{  current_user.username }} profile picture">
            {% endif %}

            <span class="ml-3 font-medium font-serif dark:text-slate-200 ">{{ current_user.username[0]|upper}}{{current_user.username[1:] }}</span>
          </a>        
      {% endif %}

      <button data-collapse-toggle="navbar-default" type="button"
        class="inline-flex items-center p-2 ml-3 rounded-md md:hidden text-pink-100 bg-pink-300 hover:bg-pink-400 dark:bg-slate-600 dark:text-slate-100 dark:hover:bg-slate-700"
        aria-controls="navbar-default" aria-expanded="false">

        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"></path>
        </svg>
      </button>

    <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="navbar-default">

    
          <ul
            class="flex flex-col md:flex-row dark:bg-slate-800">

            {% if current_user.is_authenticated %}
            <li class="my-2">
              <a href="{{ url_for('auth.logout') }}"
                class="px-6 py-3 text-white bg-pink-300 rounded-full border-4 hover:bg-pink-400 w-fit flex justify-center ml-5 dark:bg-slate-600 dark:hover:bg-slate-700">Log
                Out</a>
            </li>
            {% endif %}

            
            {% if current_user.is_authenticated and current_user.is_admin %}
            <li class="my-2">
            <a href="{{ url_for('admin.index') }}"
                  class="px-6 py-3 text-white bg-pink-300 rounded-full border-4 hover:bg-pink-400 w-fit flex justify-center ml-5 dark:bg-slate-600 dark:hover:bg-slate-700">Admin
              Dashboard</a>
            </li>
            {% endif %}

            <li class="my-2">
            <button id="theme-toggle" type="button" class="py-3 text-white bg-pink-300 rounded-full hover:bg-pink-400 
                      w-14 flex justify-center ml-5 border-4 dark:bg-slate-600 dark:hover:bg-slate-700">
            
              <div class="hidden" id="theme-toggle-dark-icon">
                <i class="fa-solid fa-moon"></i>
              </div>
            
              <div class="hidden" id="theme-toggle-light-icon">
                <i class="fa-solid fa-sun dark:bg-slate-600 dark:hover:bg-slate-700"></i>
              </div>
            
            </button>
            </li>

          </ul>

    </div>
  </div>
</nav>